# Generated by Django 6.1.1 on 2026-10-06 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Paracetamol Genfar, Ibuprofeno BSN', max_length=150, verbose_name='Nombre comercial')),
                ('brand_or_laboratory', models.CharField(blank=True, max_length=100, verbose_name='Laboratorio / Marca')),
                ('concentration', models.CharField(help_text='Ej: 500 mg, 10 mg/ml, 5%', max_length=50, verbose_name='Concentración')),
                ('presentation', models.CharField(choices=[('TAB', 'Tableta / Comprimido'), ('CAP', 'Cápsula'), ('SYR', 'Jarabe / Solución'), ('INJ', 'Inyectable'), ('CRM', 'Crema / Pomada'), ('DRP', 'Gotas'), ('INH', 'Inhalador'), ('OTH', 'Otro')], default='TAB', max_length=3, verbose_name='Presentación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Indicaciones')),
                ('contraindications', models.TextField(blank=True, verbose_name='Contraindicaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Paciente')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medicines_m_name_61a774_idx')],
            },
        ),
    ]
