# Generated by Django 6.1.1 on 2026-10-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Ej: Paracetamol, Ibuprofeno', max_length=150, verbose_name='Nombre genérico'),
        ),
    ]
